### PR TITLE
Fix: Don't double unwrap config

### PR DESCRIPTION
**Pull request by grahamtt**
Config values passed via `pyproject.toml` weren't being found because the config was being unwrapped twice.

## What

Remove an unnecessary call to `get_ruff_config`.

## Why

The extra call was preventing config values from being applied.

## References

N/A

## Checklist

- [ X ] Tests

### CODE REVIEW

**Comment by bjoernricks** [comment]
Hi,

I had a look into the [config code](https://github.com/greenbone/autohooks/blob/main/autohooks/config.py) and I am really sure you get the root of the pyproject.toml config. Thus `tools.autohooks.ruff` still must be used and I am not sure why it didn't work for you.

**Comment by grahamtt** [comment]
The issue is we're calling `get_ruff_config` at [line 40](https://github.com/greenbone/autohooks-plugin-ruff/blob/debfaec7119a4c4438934ff9529525b4b56cd031/autohooks/plugins/ruff/ruff.py#L40) and at [line 61](https://github.com/greenbone/autohooks-plugin-ruff/blob/debfaec7119a4c4438934ff9529525b4b56cd031/autohooks/plugins/ruff/ruff.py#L61). We only need one of those. I opted to keep the latter.

**Comment by bjoernricks** [comment]
> The issue is we're calling `get_ruff_config` at [line 40](https://github.com/greenbone/autohooks-plugin-ruff/blob/debfaec7119a4c4438934ff9529525b4b56cd031/autohooks/plugins/ruff/ruff.py#L40) and at [line 61](https://github.com/greenbone/autohooks-plugin-ruff/blob/debfaec7119a4c4438934ff9529525b4b56cd031/autohooks/plugins/ruff/ruff.py#L61). We only need one of those. I opted to keep the latter.

Oh why didn't I see that 🤔 ? Thanks for taking care!

**Comment by bjoernricks** [comment]
The tests are currently failing. Could you fix them? Afterwards I would love to create a new release with your changes.

**Review by y0urself — APPROVED** [review]

**Comment by bjoernricks** [comment]
Thanks a lot!

**Pull request merged**
